[package]
name = "siren"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
chrono = "0.4.42"

[lints.clippy]
needless_return = "allow"
